routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
})->name('regresar');

Route::get('/plantilla-menu', function(){
    return view('plantilla-menu');
});

Route::get('/plantilla-login', function(){
    return view('plantilla-login');
});

Route::get('/administrador', function(){
    return view('administrador');
})->name('admin');

Route::get('/bienvenido-control-escolar', function(){
    return view('bienvenido-control-escolar');
})->name('bienvenida-admin');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');


/*Profesores*/

  /*Crear Profesor: crear->llama a la vista, store->almacena en la BD     */
  Route::get('/crear_profesor', 'ProfesorController@create')->name('crear_profesor');
  Route::post('/almacenar_profesor', 'ProfesorController@store')->name('almacenar_profesor');
  /*FIn crear profesor*/

  /*Tabla profesor*/
  Route::get('/tabla_profesor', 'ProfesorController@index')->name('tabla_profesor');
  Route::get('/registro_crud_profesor', 'ProfesorController@index')->name('crud_profesor');

  /*Editar profesor*/
  Route::get('/editar_profesor{Clave_profesor}','ProfesorController@edit')->name('editar_profesor');
  Route::post('/updateProfesor{Clave_profesor}', 'ProfesorController@update')->name('update_profesor');


  /*Eliminar Profesores*/
  Route::get('/destroyProfesor{Clave_profesor}', 'ProfesorController@destroy')->name('destroy_profesor');

/*
  Route::get('/registro_crud_profesores', function(){
      return view('registro_crud_profesores');
  })->name('crud_profesor');
*/

/*Fin profesores*/




/*Coordinadores*/
Route::get('/coordinadores', function(){
    return view('coordinadores');
})->name('coordinador');

Route::get('/registro_crud_coordinadores', function(){
    return view('registro_crud_coordinadores');
})->name('crud_coordinador');

Route::resource('coordinador', 'CoordinadorController');

Route::get('/tabla_coordinadores', function(){
    return view('tabla_coordinadores');
})->name('tabla_coordinador');
/*Fin coordinadores*/


/*Alumnos*/

  Route::get('/registro_crud_alumnos', function(){
    return view('registro_crud_alumnos');
  })->name('crud_alumno');

  Route::get('/tabla_alumnos', function(){
      return view('tabla_alumnos');
  })->name('tabla_alumno');


/*Fin alumnos*/



/*Plan de estudios*/
Route::get('/tabla_plan_es', function(){
    return view('tabla_plan_es');
})->name('tabla_plan');
/*Plan de estudios*/







/*
<<<<<<< HEAD


Route::resource('index', 'AlumnoController');


Route::get('/menuProfesor', 'ProfesorController@menu')->name('menuProfesor');
Route::get('/indexProfesor', 'ProfesorController@index')->name('indexProfesor');
Route::get('/createProfesor', 'ProfesorController@create')->name('createProfesor');
Route::get('/editProfesor{Clave_profesor}', 'ProfesorController@edit')->name('editProfesor');
Route::post('/storeProfesor', 'ProfesorController@store')->name('storeProfesor');
Route::post('/updateProfesor{Clave_profesor}', 'ProfesorController@update')->name('updateProfesor');
  Route::get('/destroyProfesor{Clave_profesor}', 'ProfesorController@destroy')->name('destroyProfesor');
=======
>>>>>>> 761ebb6e76815341d23f78b7da1968cfbcf21e53
*/

resources/views/administrador.blade.php
@extends('layouts.plantilla-menu')
@section('content')
<div class="container">
    <div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Plan de Estudios</h5>
        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 10rem;" src="img/aula.svg" alt="">
        <p class="card-text">Ir a configuracion de plan de estudios.</p>
        <a href="{{ route('tabla_plan') }}" class="btn btn-primary">ir &rarr;</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Coordinadores</h5>
        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 10rem;" src="img/coordinacion.svg" alt="">
        <p class="card-text">Ir a configuracion de coordinadores.</p>
        <a href="{{ route('tabla_coordinador') }}" class="btn btn-primary">ir &rarr;</a>
      </div>
    </div>
  </div>
</div>
<div class="row">
<div class="col-sm-6">
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Profesores</h5>
    <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 10rem;" src="img/presentacion.svg" alt="">
    <p class="card-text">Ir a configuracion de .</p>
    <a href="{{ route('tabla_profesor') }}" class="btn btn-primary">ir &rarr;</a>
  </div>
</div>
</div>
<div class="col-sm-6">
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Alumnos</h5>
    <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 10rem;" src="img/estudiante.svg" alt="">
    <p class="card-text">Ir a alumnos.</p>
    <a href="{{ route('tabla_alumno') }}" class="btn btn-primary">ir &rarr;</a>
  </div>
</div>
</div>
</div>
@endsection

resources/views/bienvenido-control-escolar.blade.php
@extends('layouts.plantilla-menu')
@section('content')
<div class="container">
        <center>
                <div class="card">
                    <div class="text-center">
                        <img src="images/UNIVALLA.png" class="img-fluid" alt="Responsive image"></div>
                    <div class="body">
                            <h1>Bienvenido</h1>
                            <h4>Jefe Control Escolar</h4>
                    </div>
                </div>
                <div class="body">

                </div>
        </center>
</div>
@endsection

resources/views/control-esc.blade.php
@extends('layouts.plantilla-home')
@section('content')
<div class="container">
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Crear Usuario Control Escolar</h1>
    </div>
        <form class="user">
                <div class="form-group">
                    <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="Nombre(s)">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Apellido Paterno">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Apellido Materno">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Telefono">
                </div>
                <div class="form-group">
                    <h3>Sexo</h3>
                    <div class="radio">
                        <label><input type="radio" name="optradio" checked>M</label>
                    </div>
                    <div class="radio">
                         <label><input type="radio" name="optradio">F</label>
                     </div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Clave de Usuario">
                </div>
                <div class="form-group">
                  <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Correo electronico">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Contraseña">
                  </div>
                  <div class="col-sm-6">
                    <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repetir Contraseña">
                  </div>
                </div>
                <a href="#" class="btn btn-primary btn-user btn-block">
                  Registrar
                </a>
                <hr>
        </form>
</div>
@endsection

resources/views/coordinadores.blade.php
@extends('layouts.plantilla-menu')
@section('content')
	<div class="container">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			
				<div class="text-center">
					<h1 class="h4 text-gray-900 mb-4">Nuevo Coordindador</h1>
				</div>
				
						<form method="POST" action="{{ route('coordinador.store') }}"  role="form">
							{{ csrf_field() }}
							

							
									<div class="form-group">
										<input type="text" name="Nombre" id="Nombre" class="form-control form-control-user" placeholder="Nombre">
									</div>

								

							
									<div class="form-group">
										<input type="text" name="Ap_Paterno" id="Ap_Paterno" class="form-control form-control-user" placeholder="Apellido Paterno">
									</div>



                  <div class="form-group">
                    <input type="text" name="Ap_Materno" id="Ap_Materno" class="form-control form-control-user" placeholder="Apellido Materno">
                  </div>





							

							    <div class="form-group">
										<input type="tel" name="Telefono" id="Telefono" class="form-control form-control-user" placeholder="Telefono">
									</div>
							
									<div class="form-group">
										<input type="email" name="Correo" id="Correo" class="form-control form-control-user" placeholder="Correo">
									</div>
						

							<div class="form-goup" id="Sexo">
                  <h3>Sexo          </h3> 
                  <div class="radio">
                    <label><input type="radio" id="Sexo" name="Sexo" value="M" checked>Masculino  </label><br>
                  </div>
                  <div class="radio">
                    <label><input type="radio" id="Sexo" name="Sexo"  value="F">Femenino  </label>
                  </div>
              </div>

                <div class="form-group">
                  <input type="password" id="Password" name="Password" class="form-control form-control-user"  placeholder="Contraseña">
                </div>
                <div class="form-group">
                  <input type="password" id="Password1" name="Password1" class="form-control form-control-user"  placeholder="Repetir Contraseña">
                </div>
						




								<div class="col-xs-12 col-sm-12 col-md-12">
									<input type="submit"  value="Registrar" class="btn btn-primary btn-user btn-block">
								</div>
            

							</div>
						</form>
				

			
		
	</section>
	@endsection

resources/views/edicion_crud_profesor.blade.php
@extends('layouts.plantilla-menu')
@section('content')
    <div class="container">
      @if (session()->has('profe'))
        <div  class="">{{session('profe')}}</div>  <!--Darle estilo a este cuadro, que aparece despues de editar correctamente-->
      @endif
        <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Crear Profesor</h1>
                  </div>
                  <form class="user" method="POST" role="form" action="{{ route('update_profesor',$profesor->Clave_profesor) }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <input type="text" pattern="[a-zA-ZñÑáéíóúÁÉÍÓÚ\s]{3,30}" title="Formato: De 3 a 30 letras" required value="{{$profesor->Nombre}}"  name="nombre" class="form-control form-control-user"  autocomplete="off" id="nombre" placeholder="Nombre(s)">
                    </div>
                    <div class="form-group">
                        <input type="text" pattern="[a-zA-ZñÑáéíóúÁÉÍÓÚ\s]{3,45}" title="Formato: De 3 a 45 letras" required value="{{$profesor->Ap_paterno}}" class="form-control form-control-user" name="apP" id="apP" autocomplete="off" placeholder="Apellido Paterno">
                    </div>
                    <div class="form-group">
                        <input type="text" pattern="[a-zA-ZñÑáéíóúÁÉÍÓÚ\s]{3,15}" autocomplete="off" title="Formato: De 3 a 45 letras" required value="{{$profesor->Ap_materno}}" class="form-control form-control-user" id="apM" name="apM" placeholder="Apellido Materno">
                    </div>
                    <div class="form-group">
                        <input type="text" pattern="[0-9]{7,10}" title="Formato: De 7 a 10 números" autocomplete="off" required value="{{$profesor->Telefono}}" class="form-control form-control-user" name="telefono" id="telefono" placeholder="Telefono">
                    </div>
                    <div class="form-group">
                        <h3>Sexo</h3>
                        <div class="radio">
                            <label><input type="radio" name="sexo" value="M" checked>M</label>
                        </div>
                        <div class="radio">
                             <label><input type="radio" value="F" name="sexo">F</label>
                         </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" required value="{{$profesor->Cedula_profesional}}" name="cedula" id="cedula" placeholder="Cedula profesional">
                    </div>
                    <div class="form-group">
                      <input type="email"  title="Máximo 35 caracteres" class="form-control form-control-user" required value="{{$profesor->Correo}}" name="correo" id="correo" placeholder="Correo electronico">
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Contraseña">
                      </div>
                      <div class="col-sm-6">
                        <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repetir Contraseña">
                      </div>
                    </div>
                      <input type="hidden" name="estatus" id="Estatus" value="1" class="form-control input-sm" placeholder="Estatus">
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                      Editar
                    </button>
                    <hr>
                  </form>

    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/profesores.blade.php
@extends('layouts.plantilla-menu')
@section('content')
    <div class="container">

        <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Crear Profesor</h1>
                  </div>
                  <form class="user" method="POST" role="form" action="{{ route('almacenar_profesor') }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <input type="text"  name="nombre" class="form-control form-control-user" id="nombre" placeholder="Nombre(sss)">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" name="apP" id="apP" placeholder="Apellido Paterno">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="apM" name="apM" placeholder="Apellido Materno">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" name="telefono" id="telefono" placeholder="Telefono">
                    </div>
                    <div class="form-group">
                        <h3>Sexo</h3>
                        <div class="radio">
                            <label><input type="radio" name="sexo" value="M" checked>M</label>
                        </div>
                        <div class="radio">
                             <label><input type="radio" value="S" name="sexo">F</label>
                         </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" name="cedula" id="cedula" placeholder="Cedula profesional">
                    </div>
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" name="correo" id="correo" placeholder="Correo electronico">
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Contraseña">
                      </div>
                      <div class="col-sm-6">
                        <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repetir Contraseña">
                      </div>
                    </div>
                      <input type="hidden" name="estatus" id="Estatus" value="1" class="form-control input-sm" placeholder="Estatus">
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                      Registrara
                    </button>
                    <hr>
                  </form>

    </div>
@endsection

resources/views/registro_crud_alumnos.blade.php
@extends('layouts.plantilla-menu')
@section('content')
    <div class="container">
        <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Crear Usuario Alumno</h1>
                  </div>
                  <form class="user">
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="Nombre(s)">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Apellido Paterno">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Apellido Materno">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Telefono">
                    </div>
                    <div class="form-group">
                        <h3>Sexo</h3>
                        <div class="radio">
                            <label><input type="radio" name="optradio" checked>M</label>
                        </div>
                        <div class="radio">
                             <label><input type="radio" name="optradio">F</label>
                         </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Clave de Usuario">
                    </div>
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Correo electronico">
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Contraseña">
                      </div>
                      <div class="col-sm-6">
                        <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repetir Contraseña">
                      </div>
                    </div>
                    <a href="#" class="btn btn-primary btn-user btn-block">
                      Registrar
                    </a>
                    <hr>
                  </form>
    </div>
    <script type="text/javascript">
           $(function () {
               $('#datetimepicker5').datetimepicker({
                   defaultDate: "11/1/2013",
                   disabledDates: [
                       moment("12/25/2013"),
                       new Date(2013, 11 - 1, 21),
                       "11/22/2013 00:53"
                   ]
               });
           });
       </script>
@endsection

resources/views/registro_crud_coordinadores.blade.php
@extends('layouts.plantilla-menu')
@section('content')
    <div class="container">
        <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Crear Usuario Coordinadores</h1>
                  </div>
                  <form class="user">
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="Nombre(s)">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Apellido Paterno">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Apellido Materno">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Telefono">
                    </div>
                    <div class="form-group">
                        <h3>Sexo</h3>
                        <div class="radio">
                            <label><input type="radio" name="optradio" checked>M</label>
                        </div>
                        <div class="radio">
                             <label><input type="radio" name="optradio">F</label>
                         </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Clave de Usuario">
                    </div>
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Correo electronico">
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Contraseña">
                      </div>
                      <div class="col-sm-6">
                        <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repetir Contraseña">
                      </div>
                    </div>
                    <a href="#" class="btn btn-primary btn-user btn-block">
                      Registrar
                    </a>
                    <hr>
                  </form>
    </div>
    <script type="text/javascript">
           $(function () {
               $('#datetimepicker5').datetimepicker({
                   defaultDate: "11/1/2013",
                   disabledDates: [
                       moment("12/25/2013"),
                       new Date(2013, 11 - 1, 21),
                       "11/22/2013 00:53"
                   ]
               });
           });
       </script>
@endsection

resources/views/tabla_alumnos.blade.php
@extends('layouts.plantilla-menu')
@section('content')
<div class="main-content">
    <div class="section__content section__content--p1250">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!-- DATA TABLE -->
                    <h3 class="title-12 m-b-12">Tabla de Alumnos</h3>
                    <div class="table-data__tool">
                        <div class="table-data__tool-left">
                        </div>
                        <div class="table-data__tool-right">
                            <button class="au-btn au-btn-icon au-btn--green au-btn--small">
                                <i class="zmdi zmdi-plus"></i>Agregar Usuario</button>
                            <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                                <!--<select class="js-select2" name="type">
                                    <option selected="selected">Export</option>
                                    <option value="">Option 1</option>
                                    <option value="">Option 2</option>
                                </select>-->

                            </div>
                        </div>
                    </div>
                    <!-- Start Table -->
                    <div class="card text-center">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nombre(s)</th>
                                            <th>Ap_Paterno</th>
                                            <th>Ap_Materno</th>
                                            <th>Telefono</th>
                                            <th>Correo</th>
                                            <th>Red_Social</th>
                                            <th>Sexo</th>
                                            <th>Estado</th>
                                            <th>Fecha_A</th>
                                            <th>Fecha_E</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>18026410</td>
                                            <td>Lori</td>
                                            <td>Hernandez</td>
                                            <td>Lopez</td>
                                            <td>4432183105</td>
                                            <td>lori@example.com
                                            </td>
                                            <td>Lory Galaxys</td>
                                            <td>M</td>
                                            <td>Activo</td>
                                            <td>29-Marzo-2019:12:15:PM</td>
                                            <td>29-Marzo-2019:1:15:AM</td>
                                            <td>
                                                <div class="table-data-feature">
                                                    <button class="item" data-toggle="tooltip" data-placement="top" title="Editar">
                                                        <i class="zmdi zmdi-edit"></i>
                                                    </button>
                                                    <button class="item" data-toggle="tooltip" data-placement="top" title="Eliminar">
                                                        <i class="zmdi zmdi-delete"></i>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr class="spacer"></tr>
                                    </tbody>
                                    <!--Table body-->
                                </table>
                                <!--Table-->
                            </div>
                        </div>
                        <div class="card-footer text-muted"></div>
                    </div>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection